### ISSUE TITLE
Running firmware could not be detected

### ISSUE THREAD

**Issue by rouke-broersma** [darkxst/sl-test#1]
I'm following [this](https://smarthomescene.com/guides/how-to-enable-thread-and-matter-support-on-sonoff-zbdongle-e/) guide to flash my new Sonoff ZBDongle-E with the multiprotocol firmware, however your flasher gives this error message:

![image](https://github.com/darkxst/sl-test/assets/3595932/b5393c78-49e0-4aa7-836c-e4b675b1f007)

The debug log shows this:

```
2023-06-04 15:46:20 emscripten universal_silabs_flasher.flasher[42] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
```

I have confirmed that the device is recognized:

``` 
> lsusb
> Bus 003 Device 009: ID 1a86:55d4 QinHeng Electronics SONOFF Zigbee 3.0 USB Dongle Plus V2
``` 

Do you have any advice for what I should try next? There aren't really a lot of resources on this topic yet and I am basically an end-user in this regard.

**Comment by darkxst** [comment]
@rouke-broersma Make sure there are no other active connections to the dongle, such as ZHA or Zigbee2MQTT.

That log message is not particularly useful, however if you are still having trouble, try the manual flashing method using [Universal-silabs-flasher](https://github.com/NabuCasa/universal-silabs-flasher) as covered in my blog here:
https://dialedin.com.au/blog/sonoff-zbdongle-e-rcp-firmware#flashing-the-dongle

This is the same tool used under the hood by the web flasher, but running it directly should provide more detailed logs.

**Comment by rouke-broersma** [comment]
I think I found the issue with your blogpost, thank you.

The issue was that `/dev/ttyACM0` permission was set to root only, so `universal-silabs-flasher` threw an unauthorized exception. This is imo most likely the same problem in the browser except the error message was swallowed somewhere.

**Comment by darkxst** [comment]
Ah yes, permissions on serial devices may vary depending on OS.
Atleast on Ubuntu and Debian there is a `dialout` group that the user would need to be a member of, to gain access to serial devices!

**Comment by Morganizer** [comment]
For me on Fedora, running `sudo chmod 777 /dev/ttyACM0` then let me run the web upgrade successfully.
Thank you!

**Comment by darkxst** [comment]
As per my previous comment, use should just add your user to the `dialout` group. It appears is should also work for Fedora.
